// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

public class TestySelenium {
    private WebDriver driver;
    // tag Before oznacza, że metoda setUp wykona się pzed testem

    @Before
    public void setUp() {
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
    }
    // quit to wyjście z przeglądarki - taka metoda powinna być na końcu testów
    // tag After oznacza, że wykona się po teście

    @After
    public void tearDown() {
        driver.quit();
    }

    // Słuzy do pominięcia testu
    @Ignore
    @Test
    public void dodanieTekstuDoInitial() throws InterruptedException {
        // get otwiera stronę internetową, strona musi być podana w stringach
        driver.get("http://executeautomation.com/demosite/index.html");
        // do wyszukiwania elementów służy metoda findElement
        WebElement initial = driver.findElement(By.id("Initial"));
        initial.sendKeys("Test");
        Thread.sleep(3000);
    }

    @Ignore
    @Test
    public void wstawImieINazwisko() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        // krok 1 Wstaw tekst do First Name
        WebElement imie = driver.findElement(By.id("FirstName"));
        imie.sendKeys("Joasia");
        Thread.sleep(3000);
        // krok 2 Wstaw tekst do Middle Name
        WebElement nazwisko = driver.findElement(By.id("MiddleName"));
        nazwisko.sendKeys("Mroczek");
        Thread.sleep(3000);
    }

    @Ignore
    @Test
    public void zaznaczCheckbox() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        Thread.sleep(2000);
        // krok 1 odznacz checkbox English
        WebElement checkboxEnglish = driver.findElement(By.name("english"));
        checkboxEnglish.click();
        Thread.sleep(2000);
        // krok 2 zaznacz checkbox Hindi
        WebElement chceckboxHindi = driver.findElement(By.name("Hindi"));
        chceckboxHindi.click();
        Thread.sleep(2000);
    }
    // test logowania

    @Test
    public void logowanie() throws InterruptedException {
        driver.get("http://newtours.demoaut.com/index.php");
        // krok 1 Wpisz imię
        WebElement name = driver.findElement(By.name("userName"));
        name.sendKeys("Joasia");
        Thread.sleep(2000);
        // krok 2 Wpisz hasło
        WebElement password = driver.findElement(By.name("password"));
        password.sendKeys("blabla");
        Thread.sleep(2000);
        // krok 3 Naciśnij Sign-in
        WebElement button = driver.findElement(By.name("login"));
        button.click();
        Thread.sleep(2000);
    }

    @Ignore
    @Test
    public void dropDown() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        Thread.sleep(2000);
        // dropdown = select - rozwijana lista
        Select dropdown = new Select(driver.findElement(By.id("TitleId")));
        //dropdown.selectByVisibleText("Mr.");
        //dropdown.selectByIndex(2);
        dropdown.selectByValue("2");
        Thread.sleep(2000);
    }

    @Test
    public void multipleChoice() throws InterruptedException {
        driver.get("http://output.jsbin.com/osebed/2");
        Thread.sleep(2000);
        // Stworzyć element selecta
        Select multipleChoice = new Select(driver.findElement(By.id("fruits")));
        // wybrać po value
        //multipleChoice.selectByValue("orange");
        // wybrać po visible text
        multipleChoice.selectByVisibleText("banana");
        Thread.sleep(3000);
    }

    @Test
    public void linkText() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        Thread.sleep(2000);
        // Znaleźliśmy element, który jest podlinkowany, jest to 1 słowo + klikneliśmy wen element
        WebElement linkText = driver.findElement(By.linkText("HtmlPopup"));
        linkText.click();
        Thread.sleep(3000);

    }

    @Test
    public void partialLink() throws InterruptedException {
        driver.get("http://newtours.demoaut.com/index.php");
        Thread.sleep(2000);
        // tworzymy element partialLink
        WebElement partialLink = driver.findElement(By.partialLinkText("SIGN"));
        partialLink.click();
        Thread.sleep(2000);

    }

    @Ignore
    @Test
    public void alertAccepted() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        Thread.sleep(2000);
        // klikamy w button generate
        WebElement button = driver.findElement(By.name("generate"));
        button.click();
        Thread.sleep(2000);
        // Musimy się przełączyć na alert
        Alert alertElement = driver.switchTo().alert();
        // chcemy kliknąć OK na alercie
        alertElement.accept();
        Thread.sleep(3000);
        alertElement.accept();
        Thread.sleep(3000);
    }

    @Test
    public void alertDismiss() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        Thread.sleep(2000);
        // klikamy w button generate
        WebElement button = driver.findElement(By.name("generate"));
        button.click();
        Thread.sleep(2000);
        // Musimy się przełączyć na alert
        Alert alertElement = driver.switchTo().alert();
        // chcemy kliknąć OK na alercie
        alertElement.dismiss();
        Thread.sleep(3000);
        alertElement.accept();
        Thread.sleep(3000);
    }

    @Test
    public void radioButton() throws InterruptedException {
        driver.get("http://demo.guru99.com/test/radio.html");
        Thread.sleep(2000);
        // stworzymy 3 radio buttony
        WebElement radio1 = driver.findElement(By.id("vfb-7-1"));
        WebElement radio2 = driver.findElement(By.id("vfb-7-2"));
        WebElement radio3 = driver.findElement(By.id("vfb-7-3"));
        // klimy na wybrany radio3 button  a następnie na radio2
        radio3.click();
        Thread.sleep(2000);
        radio2.click();
        Thread.sleep(2000);
    }

    @Test
    public void wyczyscOkno() throws InterruptedException {
        driver.get("http://executeautomation.com/demosite/index.html");
        Thread.sleep(2000);
        // stwórz 2 elementy dla Initial i First Name
        WebElement initial = driver.findElement(By.id("Initial"));
        WebElement firstName = driver.findElement(By.id("FirstName"));
        // wstaw tekst do elementów
        initial.sendKeys("JM");
        firstName.sendKeys("Joasia");
        Thread.sleep(3000);
        // wyczyść okna
        initial.clear();
        Thread.sleep(2000);
        firstName.clear();
        Thread.sleep(2000);
    }


    @Test
    public void googletry() throws InterruptedException {


        driver.get("https://www.google.pl/");
        WebElement google = driver.findElement(By.name("q"));
        google.sendKeys("ale jaja robie w selenium");
        Thread.sleep(2000);
    }

    @Test
    public void szukaj() throws InterruptedException {

        driver.get("https://www.google.pl/");
        WebElement search = driver.findElement(By.name("btnK"));
        search.click();
    }
}



